security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: 
      userAuthorizationUri: 
      tokenName: 
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: 
spring:
  resources:
    chain:
      enabled: true